language: java
jdk:
- oraclejdk8
sudo: false
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gina.debeukelaer@ordina.be
  password:
    secure: lpNO215W9c2i02eBqJyQKKMIxpUEI/T4nSaIme59f25dIsyahQLnRZn4bZn5I2tNZ8ZgoMv9hcJduxZr8HJx60mDJWoPAlbBSlUINbtjNfPMZYsNGvQgqvX6vuuYeFha4SEeMQa87MN3ms0uhDX5tPzXKZChAw8zOhlbkxJoMK5H0uZ/T8f6dIdTCY36xceTM7uuhkxGHRBW6hoXp6b7WWpGC0d+rs+i0EC/Y1ONragZxHOkuwmFFL6tM6vm4UvxWQrNjulhMBKTBoHGJ6KTXuYKZa62A5FmtcXP+PU1H+NibIMxUIZ1Gx2cJGsVOHVIF6QFrrudaKt/JviU4eJjz2JAQ3p2dfRVhhtz4zFVa6X7VPD6qlYAZuEUA7Yh8NC37rg2bn65AiDTapxjoqeOhHUcCm2RpQbnPCTmurv5WJ/2YO/bgcgDi+RBsw/RUCRxZfv9yjAwM9aK2BODextb4fdUzpBGjpvdvcrkSpsscwMIfiqieLlGU2m15UjfsTG9r9+6utMq6bUe8cKQMu9Ersz3+IVdtd4hhq8NohuoTR8QM1gFFsX6PF3GUn1dvYVJ1OM2eWfEgsNxjS+CQKxwTabrCbuQJlHDirxm9+Q2OwI3806zv46vPBJOAJbb4gAaQYY344xCI0YOXvMxa4Yun5oICFtDCsxHGGCTMFzT9SY=
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/turbine
    branch: master
after_deploy:
- mvn clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: BHPz9yrZ28UhkyN51mpvh9vryioCji8VEYLExrxQ6weWIEvYJN4rQ+bubB71nkD7lw5rEh7xx7Lny7DVHTWhf+4HDe4h2nI8L1KqC/SpFbnMrsyThZS1fA9AfwSsujVUuykNAXNu6SpjalBkd+B91P34RQ1I+torC6uft56KPHsiYJbv+Su7yCV6BBaLbR6U9tQjKmKBo3BYah5b87DvISHtJQWM5IwhS2NCk6hYtQ8uIXciiL4E21MCip20IUx0cwL4Wc+QQQkkzc2qGtobK+ptAsMmAQpfcxpBIaXJ0oyb81QSfkZpw31fPFEEey8v8B6iOF50kgWIXOdFCUKALCAXTNdIfZasjdGNohlxWD9UAA0wHWi42qvysYJDUdDJqiwHLKqbmhPZHagmT4/SIud/rwUT3o7Fx9wbUKSZ2ZgXaEUiJ0dQCQFxnZj8NS0HLqASxMFhNAf44pf/R/0fmCSiAU8dIeKND5tCccuUtcm8r2IsCzJT2T7yLceyrfWCjPlQG5ui5qD2nDmjvwB8vbHWsmo+TYQ/dM07Ba4FjjgDbQ+pLR7K6pHEMrXQrB7ChwyZG/6ouwxTfdQp9v4oaPGWJHDpaTVEQonRaIUDThkep0/tUi1S5tSREcGwfZAEa/1fhMVaoWQlqBjQJf0Tvxb6oWXdn5pGhvcAaxfAw6U=
